DELIMITER $$
USE `group3_miniproject`$$
CREATE PROCEDURE GET_CUSTOMER_DELIVERY_HISTORY()
BEGIN
WITH SENDER AS (
  SELECT COUNT(*) AS SENT
  FROM CUSTOMERS A
  INNER JOIN DELIVERY_DETAILS B ON A.ID = B.SENDER_ID
  INNER JOIN PACKAGES C ON B.ID = C.DELIVERY_DETAILS_ID
  INNER JOIN TRACKING_EVENTS D ON C.ID = D.PACKAGE_ID
  WHERE D.PACKAGE_STATUS = 'DELIVERED'
  AND A.ID = CUSTOMER_ID
),
RECEIVER AS (
  SELECT COUNT(*) AS RECEIVED
  FROM CUSTOMERS A 
  INNER JOIN DELIVERY_DETAILS B ON A.ID = B.RECIPIENT_ID
  INNER JOIN PACKAGES C ON B.ID = C.DELIVERY_DETAILS_ID
  INNER JOIN TRACKING_EVENTS D ON C.ID = D.PACKAGE_ID
  WHERE D.PACKAGE_STATUS = 'DELIVERED'
  AND A.ID = CUSTOMER_ID
),
CUSTOMER_NAME AS(
  SELECT CONCAT(FIRST_NAME, ' ',LAST_NAME) AS FULL_NAME
  FROM CUSTOMERS
  WHERE ID = CUSTOMER_ID
)
SELECT   CONCAT('CUSTOMER NAME: ', C.FULL_NAME) AS FULL_NAME, 
    CONCAT('TOTAL PACKAGES SENT: ', A.SENT) AS SENT, 
        CONCAT('TOTAL PACKAGES RECEIVED: ',B.RECEIVED) AS RECEIVED
FROM SENDER A, RECEIVER B, CUSTOMER_NAME C;



SELECT C.ID, C.DELIVERY_DATE, C.PACKAGE_TYPE, D.PACKAGE_STATUS, CONCAT(E.FIRST_NAME, ' ',E.LAST_NAME) AS COURIER_NAME
FROM DELIVERY_DETAILS B 
INNER JOIN PACKAGES C ON B.ID = C.DELIVERY_DETAILS_ID
INNER JOIN TRACKING_EVENTS D ON C.ID = D.PACKAGE_ID
INNER JOIN COURIERS E ON C.COURIER_ID = E.ID
WHERE  D.PACKAGE_STATUS = 'DELIVERED' 
AND B.ID IN (
  SELECT ID FROM delivery_details
  WHERE recipient_id = CUSTOMER_ID
  OR sender_id = CUSTOMER_ID);
  
END$$

DELIMITER ;

CALL getMostActiveDeliveryCities();