# Updated application.yml for H2 Database

YAML
# src/main/resources/application.yml
server:
  port: 8081 # Port for the cargo service

spring:
  application:
    name: cargo-service # Name of our application (useful for microservices)
  datasource:
    url: jdbc:h2:mem:cargodb # In-memory H2 database URL
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect # Dialect for H2
    hibernate:
      ddl-auto: update # Automatically update schema (create tables if not exist)
  h2:
    console:
      enabled: true # Enable H2 console for viewing database content
      path: /h2-console # Path to access H2 console
