spring:
    application:
        name: mini-project

    datasource:
        url: jdbc:mysql://localhost:3306/cargoshippingsystem
        username: root
        password:
        driver-class-name: com.mysql.cj.jdbc.Driver