--NUMBER 1
SELECT PRODUCT_TYPE, COUNT(*) AS total_products
FROM PRODUCT
GROUP BY PRODUCT_TYPE;

--NUMBER 2
SELECT FIRST_NAME, SURNAME
FROM CUSTOMER
WHERE LOWER(CITY) LIKE '%a%';

--NUMBER 3
SELECT *
FROM `ORDER`
WHERE MONTH(DATE_ORDERED) BETWEEN 1 AND 8;

--NUMBER 4
SELECT p1.*
FROM PRODUCT p1
WHERE PRICE = (
    SELECT MAX(PRICE)
    FROM PRODUCT p2
    WHERE p2.PRODUCT_TYPE = p1.PRODUCT_TYPE
);

--NUMBER 5
SELECT o.*
FROM `ORDER` o
JOIN CUSTOMER c ON o.CUSTOMER_ID = c.CUSTOMER_ID
WHERE YEAR(DATE_ORDERED) = (
    SELECT MAX(YEAR(DATE_ORDERED)) FROM `ORDER`
)
AND c.EMAIL LIKE '%@gmail.com';