spring:
    application:
        name: mini-project

    datasource:
        url: jdbc:mysql://localhost:3306/cargo_shipping_system
        username: root
        password: admin
        driver-class-name: com.mysql.cj.jdbc.Driver