spring:
  datasource:
    url: jdbc:mysql://localhost:3306/taskmanager
    username: taskapp
    password: password123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    user:
      name: user
      password: user
server:
  port: 8080
