# Configuration File
# We'll configure the server port for our cargo service

#YAML
# src/main/resources/application.yml
# server:
#  port: 8081 # Set the port for the cargo service

spring:
  datasource:
    url: jdbc:h2:mem:cargodb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2-console

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
