INSERT INTO `packageTypes` (`id`,`name`) VALUES (1,'BAGS');
INSERT INTO `packageTypes` (`id`,`name`) VALUES (2,'BALE  COMPRESSED');
INSERT INTO `packageTypes` (`id`,`name`) VALUES (3,'BASE BOX');
INSERT INTO `packageTypes` (`id`,`name`) VALUES (4,'BASKET');
INSERT INTO `packageTypes` (`id`,`name`) VALUES (5,'BEER CRATE');
INSERT INTO `packageTypes` (`id`,`name`) VALUES (6,'BIN');
INSERT INTO `packageTypes` (`id`,`name`) VALUES (7,'BOARD');
INSERT INTO `packageTypes` (`id`,`name`) VALUES (8,'BOBBIN');
INSERT INTO `packageTypes` (`id`,`name`) VALUES (9,'BOLT');
INSERT INTO `packageTypes` (`id`,`name`) VALUES (10,'BOTTLE  NON PROTECTED  BOLBOUS');
INSERT INTO `packageTypes` (`id`,`name`) VALUES (11,'BOTTLE  NON PROTECTED  CYLINDRICAL');
INSERT INTO `packageTypes` (`id`,`name`) VALUES (12,'BOX');
INSERT INTO `packageTypes` (`id`,`name`) VALUES (13,'BUCKET');
INSERT INTO `packageTypes` (`id`,`name`) VALUES (14,'BULK');
INSERT INTO `packageTypes` (`id`,`name`) VALUES (15,'BULK  LIQUID');
INSERT INTO `packageTypes` (`id`,`name`) VALUES (16,'BULK  SOLID  LARGE PARTICLES');
INSERT INTO `packageTypes` (`id`,`name`) VALUES (17,'BULK  SOLID GRANULAR PARTICLES (\"GRAINS\"\")\"');
INSERT INTO `packageTypes` (`id`,`name`) VALUES (18,'BULK SOLID FINE PARTICLES (\"POWDERS\"\")\"');
INSERT INTO `packageTypes` (`id`,`name`) VALUES (19,'BUNDLE');
INSERT INTO `packageTypes` (`id`,`name`) VALUES (20,'CAN  CYLINDRICAL');
INSERT INTO `packageTypes` (`id`,`name`) VALUES (21,'CAN  RECTANULAR');
INSERT INTO `packageTypes` (`id`,`name`) VALUES (22,'CANVAS');
INSERT INTO `packageTypes` (`id`,`name`) VALUES (23,'CARBOY PROTECTED');
INSERT INTO `packageTypes` (`id`,`name`) VALUES (24,'CARTON');
INSERT INTO `packageTypes` (`id`,`name`) VALUES (25,'CASE');
INSERT INTO `packageTypes` (`id`,`name`) VALUES (26,'CASK');
INSERT INTO `packageTypes` (`id`,`name`) VALUES (27,'CHEST');
INSERT INTO `packageTypes` (`id`,`name`) VALUES (28,'COIL');
INSERT INTO `packageTypes` (`id`,`name`) VALUES (29,'COLLAPSIBLE TUBE');
INSERT INTO `packageTypes` (`id`,`name`) VALUES (30,'CRATE');
INSERT INTO `packageTypes` (`id`,`name`) VALUES (31,'CYLINDER');
INSERT INTO `packageTypes` (`id`,`name`) VALUES (32,'DEMIJOHN  NON-PROTECTED');
INSERT INTO `packageTypes` (`id`,`name`) VALUES (33,'DEMIJOHN  PROTECTED');
INSERT INTO `packageTypes` (`id`,`name`) VALUES (34,'DISPENSER');
INSERT INTO `packageTypes` (`id`,`name`) VALUES (35,'DRUM');
INSERT INTO `packageTypes` (`id`,`name`) VALUES (36,'ENVELOPE');
INSERT INTO `packageTypes` (`id`,`name`) VALUES (37,'FILMPACK');
INSERT INTO `packageTypes` (`id`,`name`) VALUES (38,'FIRKIN');
INSERT INTO `packageTypes` (`id`,`name`) VALUES (39,'FLASK');
INSERT INTO `packageTypes` (`id`,`name`) VALUES (40,'FOOTLOCKER');
INSERT INTO `packageTypes` (`id`,`name`) VALUES (41,'FRAME');
INSERT INTO `packageTypes` (`id`,`name`) VALUES (42,'FRAMED CRATE');
INSERT INTO `packageTypes` (`id`,`name`) VALUES (43,'FRUIT CRATE');
INSERT INTO `packageTypes` (`id`,`name`) VALUES (44,'GAS');
INSERT INTO `packageTypes` (`id`,`name`) VALUES (45,'GAS BOTTLE');
INSERT INTO `packageTypes` (`id`,`name`) VALUES (46,'GIRDER');
INSERT INTO `packageTypes` (`id`,`name`) VALUES (47,'GIRDER  IN BUNDLE/BUNCH/TRUSS');
INSERT INTO `packageTypes` (`id`,`name`) VALUES (48,'GROSS BARREL');
INSERT INTO `packageTypes` (`id`,`name`) VALUES (49,'HAMPER');
INSERT INTO `packageTypes` (`id`,`name`) VALUES (50,'HOGSHEAD');
INSERT INTO `packageTypes` (`id`,`name`) VALUES (51,'INGOT');
INSERT INTO `packageTypes` (`id`,`name`) VALUES (52,'INGOT  IN BUNDLE/BUNCH/TRUSS');
INSERT INTO `packageTypes` (`id`,`name`) VALUES (53,'JAR');
INSERT INTO `packageTypes` (`id`,`name`) VALUES (54,'JERRICAN  CYLINDERICAL');
INSERT INTO `packageTypes` (`id`,`name`) VALUES (55,'JERRICAN  RECTANGULAR');
INSERT INTO `packageTypes` (`id`,`name`) VALUES (56,'JUG');
INSERT INTO `packageTypes` (`id`,`name`) VALUES (57,'JUTEBAG');
INSERT INTO `packageTypes` (`id`,`name`) VALUES (58,'KEG');
INSERT INTO `packageTypes` (`id`,`name`) VALUES (59,'LOG');
INSERT INTO `packageTypes` (`id`,`name`) VALUES (60,'LOG  IN BUNDLE/BUNCH/TRUSS');
INSERT INTO `packageTypes` (`id`,`name`) VALUES (61,'MAT');
INSERT INTO `packageTypes` (`id`,`name`) VALUES (62,'MATCHBOX');
INSERT INTO `packageTypes` (`id`,`name`) VALUES (63,'MILK CRATE');
INSERT INTO `packageTypes` (`id`,`name`) VALUES (64,'MULTIPLY BAG');
INSERT INTO `packageTypes` (`id`,`name`) VALUES (65,'MULTIWALL SACK');
INSERT INTO `packageTypes` (`id`,`name`) VALUES (66,'NEST');
INSERT INTO `packageTypes` (`id`,`name`) VALUES (67,'NET');
INSERT INTO `packageTypes` (`id`,`name`) VALUES (68,'PACK');
INSERT INTO `packageTypes` (`id`,`name`) VALUES (69,'PACKAGE');
INSERT INTO `packageTypes` (`id`,`name`) VALUES (70,'PACKET');
INSERT INTO `packageTypes` (`id`,`name`) VALUES (71,'PAD');
INSERT INTO `packageTypes` (`id`,`name`) VALUES (72,'PAIL');
INSERT INTO `packageTypes` (`id`,`name`) VALUES (73,'PALLET (LIFT)');
INSERT INTO `packageTypes` (`id`,`name`) VALUES (74,'PARCEL');
INSERT INTO `packageTypes` (`id`,`name`) VALUES (75,'PIPE');
INSERT INTO `packageTypes` (`id`,`name`) VALUES (76,'PIPES + PLANKS  IN BUNDLE/BUNCH/TRUSS');
INSERT INTO `packageTypes` (`id`,`name`) VALUES (77,'PITCHER');
INSERT INTO `packageTypes` (`id`,`name`) VALUES (78,'PLANK');
INSERT INTO `packageTypes` (`id`,`name`) VALUES (79,'PLATE');
