/*
-- Query: select * from trackingevent
LIMIT 0, 1000

-- Date: 2025-08-12 09:56
*/
INSERT INTO `trackingEvent` (`id`,`description`,`packageId`,`locationId`,`packageStatusId`,`courierId`) VALUES (1,'Received',65,10,1,69);
INSERT INTO `trackingEvent` (`id`,`description`,`packageId`,`locationId`,`packageStatusId`,`courierId`) VALUES (2,'In port',26,16,3,62);
INSERT INTO `trackingEvent` (`id`,`description`,`packageId`,`locationId`,`packageStatusId`,`courierId`) VALUES (3,'On hold',57,23,5,72);
INSERT INTO `trackingEvent` (`id`,`description`,`packageId`,`locationId`,`packageStatusId`,`courierId`) VALUES (4,'In port',63,73,3,2);
INSERT INTO `trackingEvent` (`id`,`description`,`packageId`,`locationId`,`packageStatusId`,`courierId`) VALUES (5,'In port',21,57,4,35);
INSERT INTO `trackingEvent` (`id`,`description`,`packageId`,`locationId`,`packageStatusId`,`courierId`) VALUES (6,'Received',6,33,1,74);
INSERT INTO `trackingEvent` (`id`,`description`,`packageId`,`locationId`,`packageStatusId`,`courierId`) VALUES (7,'On hold',79,25,5,40);
INSERT INTO `trackingEvent` (`id`,`description`,`packageId`,`locationId`,`packageStatusId`,`courierId`) VALUES (8,'Received',51,18,1,20);
INSERT INTO `trackingEvent` (`id`,`description`,`packageId`,`locationId`,`packageStatusId`,`courierId`) VALUES (9,'En route',61,74,2,47);
INSERT INTO `trackingEvent` (`id`,`description`,`packageId`,`locationId`,`packageStatusId`,`courierId`) VALUES (10,'In port',56,79,3,4);
INSERT INTO `trackingEvent` (`id`,`description`,`packageId`,`locationId`,`packageStatusId`,`courierId`) VALUES (11,'On hold',23,61,5,68);
INSERT INTO `trackingEvent` (`id`,`description`,`packageId`,`locationId`,`packageStatusId`,`courierId`) VALUES (12,'In port',32,34,4,12);
INSERT INTO `trackingEvent` (`id`,`description`,`packageId`,`locationId`,`packageStatusId`,`courierId`) VALUES (13,'In port',22,42,4,23);
INSERT INTO `trackingEvent` (`id`,`description`,`packageId`,`locationId`,`packageStatusId`,`courierId`) VALUES (14,'On hold',9,38,5,67);
INSERT INTO `trackingEvent` (`id`,`description`,`packageId`,`locationId`,`packageStatusId`,`courierId`) VALUES (15,'Late arrival',77,48,6,33);
INSERT INTO `trackingEvent` (`id`,`description`,`packageId`,`locationId`,`packageStatusId`,`courierId`) VALUES (16,'En route',27,19,2,42);
INSERT INTO `trackingEvent` (`id`,`description`,`packageId`,`locationId`,`packageStatusId`,`courierId`) VALUES (17,'Received',73,80,1,14);
INSERT INTO `trackingEvent` (`id`,`description`,`packageId`,`locationId`,`packageStatusId`,`courierId`) VALUES (18,'Late arrival',24,56,6,32);
INSERT INTO `trackingEvent` (`id`,`description`,`packageId`,`locationId`,`packageStatusId`,`courierId`) VALUES (19,'In port',5,51,3,80);
INSERT INTO `trackingEvent` (`id`,`description`,`packageId`,`locationId`,`packageStatusId`,`courierId`) VALUES (20,'Late arrival',67,26,6,28);
INSERT INTO `trackingEvent` (`id`,`description`,`packageId`,`locationId`,`packageStatusId`,`courierId`) VALUES (21,'On hold',74,37,5,31);
INSERT INTO `trackingEvent` (`id`,`description`,`packageId`,`locationId`,`packageStatusId`,`courierId`) VALUES (22,'In port',35,46,3,66);
INSERT INTO `trackingEvent` (`id`,`description`,`packageId`,`locationId`,`packageStatusId`,`courierId`) VALUES (23,'In port',8,71,4,7);
INSERT INTO `trackingEvent` (`id`,`description`,`packageId`,`locationId`,`packageStatusId`,`courierId`) VALUES (24,'In port',48,66,4,27);
INSERT INTO `trackingEvent` (`id`,`description`,`packageId`,`locationId`,`packageStatusId`,`courierId`) VALUES (25,'Late arrival',14,4,6,30);
INSERT INTO `trackingEvent` (`id`,`description`,`packageId`,`locationId`,`packageStatusId`,`courierId`) VALUES (26,'In port',69,17,4,1);
INSERT INTO `trackingEvent` (`id`,`description`,`packageId`,`locationId`,`packageStatusId`,`courierId`) VALUES (27,'In port',68,13,3,37);
INSERT INTO `trackingEvent` (`id`,`description`,`packageId`,`locationId`,`packageStatusId`,`courierId`) VALUES (28,'Late arrival',31,72,4,18);
INSERT INTO `trackingEvent` (`id`,`description`,`packageId`,`locationId`,`packageStatusId`,`courierId`) VALUES (29,'Received',29,2,1,15);
INSERT INTO `trackingEvent` (`id`,`description`,`packageId`,`locationId`,`packageStatusId`,`courierId`) VALUES (30,'Late arrival',50,7,6,57);
INSERT INTO `trackingEvent` (`id`,`description`,`packageId`,`locationId`,`packageStatusId`,`courierId`) VALUES (31,'On hold',13,65,5,3);
INSERT INTO `trackingEvent` (`id`,`description`,`packageId`,`locationId`,`packageStatusId`,`courierId`) VALUES (32,'In port',44,5,3,70);
INSERT INTO `trackingEvent` (`id`,`description`,`packageId`,`locationId`,`packageStatusId`,`courierId`) VALUES (33,'In port',12,50,3,56);
INSERT INTO `trackingEvent` (`id`,`description`,`packageId`,`locationId`,`packageStatusId`,`courierId`) VALUES (34,'In port',45,21,4,19);
INSERT INTO `trackingEvent` (`id`,`description`,`packageId`,`locationId`,`packageStatusId`,`courierId`) VALUES (35,'Received',80,30,1,6);
INSERT INTO `trackingEvent` (`id`,`description`,`packageId`,`locationId`,`packageStatusId`,`courierId`) VALUES (36,'Late arrival',19,43,6,26);
INSERT INTO `trackingEvent` (`id`,`description`,`packageId`,`locationId`,`packageStatusId`,`courierId`) VALUES (37,'Received',34,63,1,11);
INSERT INTO `trackingEvent` (`id`,`description`,`packageId`,`locationId`,`packageStatusId`,`courierId`) VALUES (38,'Late arrival',41,39,6,77);
INSERT INTO `trackingEvent` (`id`,`description`,`packageId`,`locationId`,`packageStatusId`,`courierId`) VALUES (39,'En route',25,77,2,25);
INSERT INTO `trackingEvent` (`id`,`description`,`packageId`,`locationId`,`packageStatusId`,`courierId`) VALUES (40,'Late arrival',78,60,6,10);
INSERT INTO `trackingEvent` (`id`,`description`,`packageId`,`locationId`,`packageStatusId`,`courierId`) VALUES (41,'In port',40,15,5,29);
INSERT INTO `trackingEvent` (`id`,`description`,`packageId`,`locationId`,`packageStatusId`,`courierId`) VALUES (42,'Received',54,55,1,34);
INSERT INTO `trackingEvent` (`id`,`description`,`packageId`,`locationId`,`packageStatusId`,`courierId`) VALUES (43,'In port',3,58,4,39);
INSERT INTO `trackingEvent` (`id`,`description`,`packageId`,`locationId`,`packageStatusId`,`courierId`) VALUES (44,'En route',62,64,2,21);
INSERT INTO `trackingEvent` (`id`,`description`,`packageId`,`locationId`,`packageStatusId`,`courierId`) VALUES (45,'In port',7,32,3,50);
INSERT INTO `trackingEvent` (`id`,`description`,`packageId`,`locationId`,`packageStatusId`,`courierId`) VALUES (46,'En route',76,52,2,16);
INSERT INTO `trackingEvent` (`id`,`description`,`packageId`,`locationId`,`packageStatusId`,`courierId`) VALUES (47,'On hold',59,44,5,36);
INSERT INTO `trackingEvent` (`id`,`description`,`packageId`,`locationId`,`packageStatusId`,`courierId`) VALUES (48,'In port',72,31,4,45);
INSERT INTO `trackingEvent` (`id`,`description`,`packageId`,`locationId`,`packageStatusId`,`courierId`) VALUES (49,'En route',33,62,2,61);
INSERT INTO `trackingEvent` (`id`,`description`,`packageId`,`locationId`,`packageStatusId`,`courierId`) VALUES (50,'In port',39,53,4,58);
INSERT INTO `trackingEvent` (`id`,`description`,`packageId`,`locationId`,`packageStatusId`,`courierId`) VALUES (51,'En route',30,45,2,41);
INSERT INTO `trackingEvent` (`id`,`description`,`packageId`,`locationId`,`packageStatusId`,`courierId`) VALUES (52,'Received',2,35,1,5);
INSERT INTO `trackingEvent` (`id`,`description`,`packageId`,`locationId`,`packageStatusId`,`courierId`) VALUES (53,'In port',42,68,3,43);
INSERT INTO `trackingEvent` (`id`,`description`,`packageId`,`locationId`,`packageStatusId`,`courierId`) VALUES (54,'On hold',38,8,5,55);
INSERT INTO `trackingEvent` (`id`,`description`,`packageId`,`locationId`,`packageStatusId`,`courierId`) VALUES (55,'On hold',10,11,5,51);
INSERT INTO `trackingEvent` (`id`,`description`,`packageId`,`locationId`,`packageStatusId`,`courierId`) VALUES (56,'In port',49,70,3,78);
INSERT INTO `trackingEvent` (`id`,`description`,`packageId`,`locationId`,`packageStatusId`,`courierId`) VALUES (57,'In port',55,69,3,13);
INSERT INTO `trackingEvent` (`id`,`description`,`packageId`,`locationId`,`packageStatusId`,`courierId`) VALUES (58,'Late arrival',71,3,6,63);
INSERT INTO `trackingEvent` (`id`,`description`,`packageId`,`locationId`,`packageStatusId`,`courierId`) VALUES (59,'En route',37,20,2,65);
INSERT INTO `trackingEvent` (`id`,`description`,`packageId`,`locationId`,`packageStatusId`,`courierId`) VALUES (60,'Late arrival',60,54,4,54);
INSERT INTO `trackingEvent` (`id`,`description`,`packageId`,`locationId`,`packageStatusId`,`courierId`) VALUES (61,'On hold',43,36,5,52);
INSERT INTO `trackingEvent` (`id`,`description`,`packageId`,`locationId`,`packageStatusId`,`courierId`) VALUES (62,'Received',47,47,1,22);
INSERT INTO `trackingEvent` (`id`,`description`,`packageId`,`locationId`,`packageStatusId`,`courierId`) VALUES (63,'Late arrival',1,75,6,75);
INSERT INTO `trackingEvent` (`id`,`description`,`packageId`,`locationId`,`packageStatusId`,`courierId`) VALUES (64,'Late arrival',17,22,6,24);
INSERT INTO `trackingEvent` (`id`,`description`,`packageId`,`locationId`,`packageStatusId`,`courierId`) VALUES (65,'En route',52,24,2,60);
INSERT INTO `trackingEvent` (`id`,`description`,`packageId`,`locationId`,`packageStatusId`,`courierId`) VALUES (66,'In port',11,78,3,38);
INSERT INTO `trackingEvent` (`id`,`description`,`packageId`,`locationId`,`packageStatusId`,`courierId`) VALUES (67,'En route',53,29,2,44);
INSERT INTO `trackingEvent` (`id`,`description`,`packageId`,`locationId`,`packageStatusId`,`courierId`) VALUES (68,'Received',70,67,1,46);
INSERT INTO `trackingEvent` (`id`,`description`,`packageId`,`locationId`,`packageStatusId`,`courierId`) VALUES (69,'Late arrival',4,14,6,76);
INSERT INTO `trackingEvent` (`id`,`description`,`packageId`,`locationId`,`packageStatusId`,`courierId`) VALUES (70,'Late arrival',20,27,6,79);
INSERT INTO `trackingEvent` (`id`,`description`,`packageId`,`locationId`,`packageStatusId`,`courierId`) VALUES (71,'En route',75,76,2,73);
INSERT INTO `trackingEvent` (`id`,`description`,`packageId`,`locationId`,`packageStatusId`,`courierId`) VALUES (72,'Received',36,1,1,9);
INSERT INTO `trackingEvent` (`id`,`description`,`packageId`,`locationId`,`packageStatusId`,`courierId`) VALUES (73,'Late arrival',16,49,4,53);
INSERT INTO `trackingEvent` (`id`,`description`,`packageId`,`locationId`,`packageStatusId`,`courierId`) VALUES (74,'En route',15,9,2,49);
INSERT INTO `trackingEvent` (`id`,`description`,`packageId`,`locationId`,`packageStatusId`,`courierId`) VALUES (75,'En route',58,41,2,8);
INSERT INTO `trackingEvent` (`id`,`description`,`packageId`,`locationId`,`packageStatusId`,`courierId`) VALUES (76,'En route',18,40,2,48);
INSERT INTO `trackingEvent` (`id`,`description`,`packageId`,`locationId`,`packageStatusId`,`courierId`) VALUES (77,'Received',64,12,1,17);
INSERT INTO `trackingEvent` (`id`,`description`,`packageId`,`locationId`,`packageStatusId`,`courierId`) VALUES (78,'Received',66,6,1,71);
INSERT INTO `trackingEvent` (`id`,`description`,`packageId`,`locationId`,`packageStatusId`,`courierId`) VALUES (79,'On hold',28,28,5,59);
INSERT INTO `trackingEvent` (`id`,`description`,`packageId`,`locationId`,`packageStatusId`,`courierId`) VALUES (80,'On hold',46,59,5,64);


--------------
/*
INSERT INTO `` (`description`,`packageId`,`locationId`,`packageStatusId`,`courierId`) VALUES ('Received',65,10,1,69);
INSERT INTO `` (`description`,`packageId`,`locationId`,`packageStatusId`,`courierId`) VALUES ('In port',26,16,3,62);
INSERT INTO `` (`description`,`packageId`,`locationId`,`packageStatusId`,`courierId`) VALUES ('On hold',57,23,5,72);
INSERT INTO `` (`description`,`packageId`,`locationId`,`packageStatusId`,`courierId`) VALUES ('In port',63,73,3,2);
INSERT INTO `` (`description`,`packageId`,`locationId`,`packageStatusId`,`courierId`) VALUES ('In port',21,57,4,35);
INSERT INTO `` (`description`,`packageId`,`locationId`,`packageStatusId`,`courierId`) VALUES ('Received',6,33,1,74);
INSERT INTO `` (`description`,`packageId`,`locationId`,`packageStatusId`,`courierId`) VALUES ('On hold',79,25,5,40);
INSERT INTO `` (`description`,`packageId`,`locationId`,`packageStatusId`,`courierId`) VALUES ('Received',51,18,1,20);
INSERT INTO `` (`description`,`packageId`,`locationId`,`packageStatusId`,`courierId`) VALUES ('En route',61,74,2,47);
INSERT INTO `` (`description`,`packageId`,`locationId`,`packageStatusId`,`courierId`) VALUES ('In port',56,79,3,4);
INSERT INTO `` (`description`,`packageId`,`locationId`,`packageStatusId`,`courierId`) VALUES ('On hold',23,61,5,68);
INSERT INTO `` (`description`,`packageId`,`locationId`,`packageStatusId`,`courierId`) VALUES ('In port',32,34,4,12);
INSERT INTO `` (`description`,`packageId`,`locationId`,`packageStatusId`,`courierId`) VALUES ('In port',22,42,4,23);
INSERT INTO `` (`description`,`packageId`,`locationId`,`packageStatusId`,`courierId`) VALUES ('On hold',9,38,5,67);
INSERT INTO `` (`description`,`packageId`,`locationId`,`packageStatusId`,`courierId`) VALUES ('Late arrival',77,48,6,33);
INSERT INTO `` (`description`,`packageId`,`locationId`,`packageStatusId`,`courierId`) VALUES ('En route',27,19,2,42);
INSERT INTO `` (`description`,`packageId`,`locationId`,`packageStatusId`,`courierId`) VALUES ('Received',73,80,1,14);
INSERT INTO `` (`description`,`packageId`,`locationId`,`packageStatusId`,`courierId`) VALUES ('Late arrival',24,56,6,32);
INSERT INTO `` (`description`,`packageId`,`locationId`,`packageStatusId`,`courierId`) VALUES ('In port',5,51,3,80);
INSERT INTO `` (`description`,`packageId`,`locationId`,`packageStatusId`,`courierId`) VALUES ('Late arrival',67,26,6,28);
INSERT INTO `` (`description`,`packageId`,`locationId`,`packageStatusId`,`courierId`) VALUES ('On hold',74,37,5,31);
INSERT INTO `` (`description`,`packageId`,`locationId`,`packageStatusId`,`courierId`) VALUES ('In port',35,46,3,66);
INSERT INTO `` (`description`,`packageId`,`locationId`,`packageStatusId`,`courierId`) VALUES ('In port',8,71,4,7);
INSERT INTO `` (`description`,`packageId`,`locationId`,`packageStatusId`,`courierId`) VALUES ('In port',48,66,4,27);
INSERT INTO `` (`description`,`packageId`,`locationId`,`packageStatusId`,`courierId`) VALUES ('Late arrival',14,4,6,30);
INSERT INTO `` (`description`,`packageId`,`locationId`,`packageStatusId`,`courierId`) VALUES ('In port',69,17,4,1);
INSERT INTO `` (`description`,`packageId`,`locationId`,`packageStatusId`,`courierId`) VALUES ('In port',68,13,3,37);
INSERT INTO `` (`description`,`packageId`,`locationId`,`packageStatusId`,`courierId`) VALUES ('Late arrival',31,72,4,18);
INSERT INTO `` (`description`,`packageId`,`locationId`,`packageStatusId`,`courierId`) VALUES ('Received',29,2,1,15);
INSERT INTO `` (`description`,`packageId`,`locationId`,`packageStatusId`,`courierId`) VALUES ('Late arrival',50,7,6,57);
INSERT INTO `` (`description`,`packageId`,`locationId`,`packageStatusId`,`courierId`) VALUES ('On hold',13,65,5,3);
INSERT INTO `` (`description`,`packageId`,`locationId`,`packageStatusId`,`courierId`) VALUES ('In port',44,5,3,70);
INSERT INTO `` (`description`,`packageId`,`locationId`,`packageStatusId`,`courierId`) VALUES ('In port',12,50,3,56);
INSERT INTO `` (`description`,`packageId`,`locationId`,`packageStatusId`,`courierId`) VALUES ('In port',45,21,4,19);
INSERT INTO `` (`description`,`packageId`,`locationId`,`packageStatusId`,`courierId`) VALUES ('Received',80,30,1,6);
INSERT INTO `` (`description`,`packageId`,`locationId`,`packageStatusId`,`courierId`) VALUES ('Late arrival',19,43,6,26);
INSERT INTO `` (`description`,`packageId`,`locationId`,`packageStatusId`,`courierId`) VALUES ('Received',34,63,1,11);
INSERT INTO `` (`description`,`packageId`,`locationId`,`packageStatusId`,`courierId`) VALUES ('Late arrival',41,39,6,77);
INSERT INTO `` (`description`,`packageId`,`locationId`,`packageStatusId`,`courierId`) VALUES ('En route',25,77,2,25);
INSERT INTO `` (`description`,`packageId`,`locationId`,`packageStatusId`,`courierId`) VALUES ('Late arrival',78,60,6,10);
INSERT INTO `` (`description`,`packageId`,`locationId`,`packageStatusId`,`courierId`) VALUES ('In port',40,15,5,29);
INSERT INTO `` (`description`,`packageId`,`locationId`,`packageStatusId`,`courierId`) VALUES ('Received',54,55,1,34);
INSERT INTO `` (`description`,`packageId`,`locationId`,`packageStatusId`,`courierId`) VALUES ('In port',3,58,4,39);
INSERT INTO `` (`description`,`packageId`,`locationId`,`packageStatusId`,`courierId`) VALUES ('En route',62,64,2,21);
INSERT INTO `` (`description`,`packageId`,`locationId`,`packageStatusId`,`courierId`) VALUES ('In port',7,32,3,50);
INSERT INTO `` (`description`,`packageId`,`locationId`,`packageStatusId`,`courierId`) VALUES ('En route',76,52,2,16);
INSERT INTO `` (`description`,`packageId`,`locationId`,`packageStatusId`,`courierId`) VALUES ('On hold',59,44,5,36);
INSERT INTO `` (`description`,`packageId`,`locationId`,`packageStatusId`,`courierId`) VALUES ('In port',72,31,4,45);
INSERT INTO `` (`description`,`packageId`,`locationId`,`packageStatusId`,`courierId`) VALUES ('En route',33,62,2,61);
INSERT INTO `` (`description`,`packageId`,`locationId`,`packageStatusId`,`courierId`) VALUES ('In port',39,53,4,58);
INSERT INTO `` (`description`,`packageId`,`locationId`,`packageStatusId`,`courierId`) VALUES ('En route',30,45,2,41);
INSERT INTO `` (`description`,`packageId`,`locationId`,`packageStatusId`,`courierId`) VALUES ('Received',2,35,1,5);
INSERT INTO `` (`description`,`packageId`,`locationId`,`packageStatusId`,`courierId`) VALUES ('In port',42,68,3,43);
INSERT INTO `` (`description`,`packageId`,`locationId`,`packageStatusId`,`courierId`) VALUES ('On hold',38,8,5,55);
INSERT INTO `` (`description`,`packageId`,`locationId`,`packageStatusId`,`courierId`) VALUES ('On hold',10,11,5,51);
INSERT INTO `` (`description`,`packageId`,`locationId`,`packageStatusId`,`courierId`) VALUES ('In port',49,70,3,78);
INSERT INTO `` (`description`,`packageId`,`locationId`,`packageStatusId`,`courierId`) VALUES ('In port',55,69,3,13);
INSERT INTO `` (`description`,`packageId`,`locationId`,`packageStatusId`,`courierId`) VALUES ('Late arrival',71,3,6,63);
INSERT INTO `` (`description`,`packageId`,`locationId`,`packageStatusId`,`courierId`) VALUES ('En route',37,20,2,65);
INSERT INTO `` (`description`,`packageId`,`locationId`,`packageStatusId`,`courierId`) VALUES ('Late arrival',60,54,4,54);
INSERT INTO `` (`description`,`packageId`,`locationId`,`packageStatusId`,`courierId`) VALUES ('On hold',43,36,5,52);
INSERT INTO `` (`description`,`packageId`,`locationId`,`packageStatusId`,`courierId`) VALUES ('Received',47,47,1,22);
INSERT INTO `` (`description`,`packageId`,`locationId`,`packageStatusId`,`courierId`) VALUES ('Late arrival',1,75,6,75);
INSERT INTO `` (`description`,`packageId`,`locationId`,`packageStatusId`,`courierId`) VALUES ('Late arrival',17,22,6,24);
INSERT INTO `` (`description`,`packageId`,`locationId`,`packageStatusId`,`courierId`) VALUES ('En route',52,24,2,60);
INSERT INTO `` (`description`,`packageId`,`locationId`,`packageStatusId`,`courierId`) VALUES ('In port',11,78,3,38);
INSERT INTO `` (`description`,`packageId`,`locationId`,`packageStatusId`,`courierId`) VALUES ('En route',53,29,2,44);
INSERT INTO `` (`description`,`packageId`,`locationId`,`packageStatusId`,`courierId`) VALUES ('Received',70,67,1,46);
INSERT INTO `` (`description`,`packageId`,`locationId`,`packageStatusId`,`courierId`) VALUES ('Late arrival',4,14,6,76);
INSERT INTO `` (`description`,`packageId`,`locationId`,`packageStatusId`,`courierId`) VALUES ('Late arrival',20,27,6,79);
INSERT INTO `` (`description`,`packageId`,`locationId`,`packageStatusId`,`courierId`) VALUES ('En route',75,76,2,73);
INSERT INTO `` (`description`,`packageId`,`locationId`,`packageStatusId`,`courierId`) VALUES ('Received',36,1,1,9);
INSERT INTO `` (`description`,`packageId`,`locationId`,`packageStatusId`,`courierId`) VALUES ('Late arrival',16,49,4,53);
INSERT INTO `` (`description`,`packageId`,`locationId`,`packageStatusId`,`courierId`) VALUES ('En route',15,9,2,49);
INSERT INTO `` (`description`,`packageId`,`locationId`,`packageStatusId`,`courierId`) VALUES ('En route',58,41,2,8);
INSERT INTO `` (`description`,`packageId`,`locationId`,`packageStatusId`,`courierId`) VALUES ('En route',18,40,2,48);
INSERT INTO `` (`description`,`packageId`,`locationId`,`packageStatusId`,`courierId`) VALUES ('Received',64,12,1,17);
INSERT INTO `` (`description`,`packageId`,`locationId`,`packageStatusId`,`courierId`) VALUES ('Received',66,6,1,71);
INSERT INTO `` (`description`,`packageId`,`locationId`,`packageStatusId`,`courierId`) VALUES ('On hold',28,28,5,59);
INSERT INTO `` (`description`,`packageId`,`locationId`,`packageStatusId`,`courierId`) VALUES ('On hold',46,59,5,64);
*/

