SELECT FIRST_NAME, LAST_NAME
FROM CUSTOMER A 
INNER JOIN LOCATION B ON A.LOCATION_ID = B.LOCATION_ID
WHERE B.CITY LIKE '%z%';

SELECT *
FROM PACKAGES
WHERE MONTH(PICKUP_DATE) BETWEEN 1 AND 8;

SELECT PACKAGE_TYPE, MAX(WEIGHT)
FROM PACKAGES
GROUP BY PACKAGE_TYPE
ORDER BY PACKAGE_TYPE;

SELECT *
FROM DELIVERY_DETAILS;

SELECT D.*
FROM CUSTOMERS A 
INNER JOIN DELIVERY_DETAILS B ON A.ID = B.RECIPIENT_ID
INNER JOIN PACKAGES D ON B.ID = D.DELIVERY_DETAILS_ID
INNER JOIN TRACKING_EVENTS E ON D.ID = E.PACKAGE_ID
WHERE A.EMAIL_ADDRESS LIKE '%@GMAIL.COM'
AND E.PACKAGE_STATUS = 'Delivered'
AND YEAR(D.PICKUP_DATE) = (
    SELECT MAX(YEAR(D.PICKUP_DATE)) 
    FROM PACKAGES
)
ORDER BY D.PICKUP_DATE DESC;

SELECT CONCAT(A.FIRST_NAME, ' ',A.LAST_NAME) AS FULL_NAME, A.ID, B.RECIPIENT_ID, B2.SENDER_ID
FROM CUSTOMERS A
INNER JOIN DELIVERY_DETAILS B ON A.ID = B.RECIPIENT_ID
INNER JOIN DELIVERY_DETAILS B2 ON A.ID = B2.SENDER_ID
INNER JOIN PACKAGES D ON B.ID = D.DELIVERY_DETAILS_ID
INNER JOIN TRACKING_EVENTS E ON D.ID = E.PACKAGE_ID
WHERE E.PACKAGE_STATUS = 'Delivered';
