

import type { Customer } from "../types/index.js";

export const mockData: Customer[] = [
  {
    id: 1,
    firstName: "John",
    lastName: "Doe",
    contactNumber: "123-456-7890",
    emailAddress: "john.doe@example.com",
    addressLine1: "123 Main Street",
    addressLine2: "Apt 4B",
    barangay: "Centro",
    city: "Manila",
    postalCode: "1000",
    region: "NCR",
    country: "Philippines",
  },
  {
    id: 2,
    firstName: "Jane",
    lastName: "Smith",
    contactNumber: "987-654-3210",
    emailAddress: "jane.smith@example.com",
    addressLine1: "456 Elm Avenue",
    addressLine2: null,
    barangay: "Poblacion",
    city: "Cebu City",
    postalCode: "6000",
    region: "Central Visayas",
    country: "Philippines",
  },
  {
    id: 3,
    firstName: "Peter",
    lastName: "Jones",
    contactNumber: "555-123-4567",
    emailAddress: "peter.jones@example.com",
    addressLine1: "789 Oak Lane",
    addressLine2: "Unit 2A",
    barangay: "Kalayaan",
    city: "Quezon City",
    postalCode: "1100",
    region: "NCR",
    country: "Philippines",
  },
  {
    id: 4,
    firstName: "Maria",
    lastName: "Garcia",
    contactNumber: "999-888-7777",
    emailAddress: "maria.garcia@example.com",
    addressLine1: "101 Pine Drive",
    addressLine2: null,
    barangay: "Sta. Cruz",
    city: "Davao City",
    postalCode: "8000",
    region: "Davao Region",
    country: "Philippines",
  },
];
