package com.example.day12;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import lombok.Data;

@Entity //tells Spring that this is a JPA entity
@Data   //lombok annotation that auto generates boilerplate code (get, set, .equals, hashCode, toString)
public class Task {
    @Id //Designates id as primary key for db
    @GeneratedValue (strategy = GenerationType.IDENTITY)    //specifies that it is auto generated by database
    private Long id;
    private String title;
    private boolean completed;
}
