CREATE DEFINER=`root`@`localhost` PROCEDURE `getRecipientPackage`(IN RECIPIENT_ID INTEGER)
BEGIN
	SELECT 
		CONCAT(CUS.FIRST_NAME,' ', CUS.LAST_NAME) AS RECIPIENT_NAME,
		PKG.PACKAGE_TYPE,
		PKG.WEIGHT,
		PKG.CONTENTS_DESCRIPTION
	FROM TRANSACTIONS AS TRNS
	INNER JOIN PACKAGES AS PKG ON TRNS.PACKAGE_ID = PKG.PACKAGE_ID
	INNER JOIN CUSTOMERS AS CUS ON TRNS.RECIPIENT_ID = CUS.CUSTOMER_ID
	WHERE TRNS.RECIPIENT_ID = RECIPIENT_ID;
END