SELECT 
  D.ID AS PACKAGE_ID,
  CONCAT(SENDER.FIRST_NAME, ' ', SENDER.LAST_NAME) AS SENDER_NAME,
  CONCAT(RECEIVER.FIRST_NAME, ' ', RECEIVER.LAST_NAME) AS RECIPIENT_NAME,
  CONCAT(E.FIRST_NAME, ' ', E.LAST_NAME) AS COURIER_NAME,
  E.VEHICLE_TYPE
FROM PACKAGES D
INNER JOIN DELIVERY_DETAILS B ON D.DELIVERY_DETAILS_ID = B.ID
INNER JOIN CUSTOMERS SENDER ON B.SENDER_ID = SENDER.ID
INNER JOIN CUSTOMERS RECEIVER ON B.RECIPIENT_ID = RECEIVER.ID
INNER JOIN COURIERS E ON D.COURIER_ID = E.ID;

SELECT C.ID, CONCAT(C.FIRST_NAME, ' ', C.LAST_NAME) AS FULL_NAME
FROM CUSTOMERS C
WHERE C.ID NOT IN(
	SELECT SENDER_ID
    FROM DELIVERY_DETAILS
);