SELECT p.PACKAGE_ID,
       CONCAT(c1.FIRST_NAME, ' ', c1.LAST_NAME)     as SENDER_NAME,
       CONCAT(c2.FIRST_NAME, ' ', c2.LAST_NAME)     as RECIPIENT_NAME,
       CONCAT(cour.FIRST_NAME, ' ', cour.LAST_NAME) as COURIER_NAME,
       cour.VEHICLE_TYPE
FROM TRANSACTIONS t
         JOIN CUSTOMERS c1 ON c1.CUSTOMER_ID = t.SENDER_ID
         JOIN CUSTOMERS c2 ON c2.CUSTOMER_ID = t.RECIPIENT_ID
         JOIN PACKAGES p ON t.PACKAGE_ID = p.PACKAGE_ID
         JOIN COURIERS cour ON cour.COURIER_ID = t.COURIER_ID;