CREATE DEFINER=`root`@`localhost` PROCEDURE `GetCustomerDeliveryHistory`(IN CUSTOMER_ID_INPUT INT)
BEGIN
    
 SELECT 
  CONCAT(FIRST_NAME ,' ', LAST_NAME) AS CUSTOMER_NAME,
  COUNT(SENDER_ID) AS TOTAL_SENT,
        (SELECT COUNT(RECIPIENT_ID) FROM CUSTOMERS
  JOIN TRANSACTIONS ON CUSTOMER_ID = RECIPIENT_ID
  WHERE CUSTOMER_ID = CUSTOMER_ID_INPUT) AS TOTAL_RECEIVED
    FROM CUSTOMERS
    JOIN TRANSACTIONS ON CUSTOMER_ID = SENDER_ID
    WHERE CUSTOMER_ID = CUSTOMER_ID_INPUT
    GROUP BY CUSTOMER_NAME;
    
    SELECT 
        CASE 
   WHEN CUS.CUSTOMER_ID = TRNS.SENDER_ID THEN 'Sent Package'
            ELSE 'Received Package'
        END AS TRANSACTION_TYPE,
  PKG.PACKAGE_ID AS PACKAGE_ID,
  TRNS.DELIVERY_DATE AS DELIVERY_DATE,
  PKG.PACKAGE_TYPE AS PACKAGE_TYPE,
  CASE
   WHEN EVT.PACKAGE_STATUS = 'In Transit' THEN 'Not Yet Delivered'
   WHEN EVT.PACKAGE_STATUS LIKE '%Delivered%' THEN 'Delivered'
   ELSE EVT.PACKAGE_STATUS
  END AS PACKAGE_STATUS,
  CONCAT(CRR.FIRST_NAME,' ', CRR.LAST_NAME) AS COURIER_NAME
 FROM CUSTOMERS AS CUS
 INNER JOIN TRANSACTIONS AS TRNS ON CUS.CUSTOMER_ID = TRNS.SENDER_ID OR CUS.CUSTOMER_ID = TRNS.RECIPIENT_ID
 INNER JOIN PACKAGES AS PKG ON TRNS.PACKAGE_ID = PKG.PACKAGE_ID
 INNER JOIN COURIERS AS CRR ON TRNS.COURIER_ID = CRR.COURIER_ID
 INNER JOIN TRACKINGEVENTS AS EVT ON PKG.PACKAGE_ID = EVT.PACKAGE_ID
 WHERE CUSTOMER_ID = CUSTOMER_ID_INPUT
    ORDER BY DELIVERY_DATE DESC;
END