#yaml
server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: file:///D:\Users\Martin\OneDrive - De La Salle University - Manila\Desktop\Personal projects\ita-bootcamp\OOCL_Team\ARELLMA_exercises\cargoapi\config-repo
