server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: file:///C:/Users/deseman/Documents/ITA-10 Bootcamp/Repository/OOCL_Team/day5/excer1/cargo-shipping-system/config-repo
