-- CREATE PROCEDURE
CREATE PROCEDURE `getPackagesforRecipient`(IN IN_RECIPIENT_ID INT)
BEGIN
	SELECT C.CUSTOMER_ID, C.FIRST_NAME, C.LAST_NAME, P.* 
	FROM PACKAGES P JOIN TRANSACTIONS T
	ON T.PACKAGE_ID = P.PACKAGE_ID
	JOIN CUSTOMERS C ON C.CUSTOMER_ID = T.RECIPIENT_ID
	WHERE T.RECIPIENT_ID = IN_RECIPIENT_ID;
END


-- IN SQL FILE
CALL getPackagesforRecipient(6);