spring:
  config:
    import: "optional:configserver:"
  application:
    name: cargo-service
  datasource:
    url: jdbc:h2:mem:cargodb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2-console
  cloud:
    config:
      server:
        git:
          uri: file:///C:/Users/deseman/Documents/ITA-10 Bootcamp/Repository/OOCL_Team/day5/excer1/cargo-shipping-system/config-repo
  profiles:
    active: native

server:
  port: 8082

