server:
  port: 8081

spring:
  profiles:
    active: dev
  config:
    import: "optional:configserver:http://localhost:8888"
  datasource:
    url: jdbc:h2:mem:cargodb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2-console

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/